apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: mlpnokgsc-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/mlpnokgsc-java-springboot-gitops